name: meety_dating_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  shared_preferences: ^2.0.17

  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0

  flutter_svg: ^1.1.6
  google_fonts: ^4.0.4
  flutter_html_table: ^3.0.0-beta.2

  syncfusion_flutter_datepicker: "20.3.57"

  chips_choice: ^3.0.0
  readmore: ^2.2.0

  path: ^1.8.2

  provider: ^6.0.5

  # firebase dependency:
  firebase_core: ^2.6.1
  firebase_auth: ^4.10.0
  firebase_messaging: ^14.2.4
  firebase_dynamic_links: ^5.0.17
  firebase_database: ^10.1.0

  #auth
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^4.3.0

  #service locator:
  get_it: ^7.2.0

  #internet
  connectivity_plus: ^3.0.3
  internet_connection_checker_plus: ^1.0.1

  #navbar
  persistent_bottom_nav_bar: ^5.0.2
  custom_navigation_bar: ^0.8.2

  #splash and icon
  flutter_native_splash: ^2.2.18

  dotted_border: ^2.0.0+3

  #local notifications:
  flutter_local_notifications: ^14.0.0+2
  action_broadcast: ^3.0.2

  # image
  image_picker: ^0.8.6+3
  flutter_image_compress: ^1.1.3
  flutter_cache_manager: ^3.3.0

  #permission_handler:
  permission_handler: ^10.2.0

  #tinder swipeable_tile:
  swipable_stack:
    git:
      url: https://github.com/Future-The-Finance-Super-App/flutter_swipable_stack.git
      ref: 88964506c110e524aa30ab92a68054036e8e7734 # branch name

  dots_indicator: ^2.1.0
  carousel_slider: ^4.2.1

  #images
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  image_cropper: ^3.0.2

  badges: ^3.0.2
  shimmer: ^2.0.0

  #circular progress
  syncfusion_flutter_gauges: ^20.4.52
  percent_indicator: ^4.2.3
  loading_animation_widget: ^1.2.0+4
  step_progress_indicator: ^1.0.2
  lottie: ^2.3.2
  multi_value_listenable_builder: ^0.0.2

  pull_to_refresh: ^2.0.0

  share_plus: ^6.3.1
  month_picker_dialog: 2.0.2
  month_year_picker: 0.3.0+1
  tuple: ^2.0.1
  dartz: ^0.10.1

  device_info_plus: ^8.1.0

  swipeable_tile: ^2.0.0+3

  #location
  geolocator: ^9.0.2
  aws_s3_upload: ^1.5.0
  drop_shadow: ^0.1.0
  flutter_dotenv: ^5.0.2
  camera: ^0.10.5+2
  reorderables: ^0.6.0
  flutter_windowmanager: ^0.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_stripe: ^9.4.0
  timeago: ^3.5.0
  another_transformer_page_view: ^2.0.1
  vector_math: ^2.1.4
  infinite_scroll_pagination: ^3.2.0
  contacts_service: ^0.6.3
  country_code_picker: ^3.0.0
  webview_flutter: ^4.4.2
  package_info_plus: ^3.1.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  light_compressor: ^2.2.0
  flutter_holo_date_picker: ^1.1.3
  sn_progress_dialog: ^1.1.3
  flutter_linkify: ^6.0.0

  flutter_easyloading:
  url_launcher:
  open_file: ^3.3.2
  crypto: ^3.0.3
  encrypt:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/icons/
    - assets/images/dummy/
    - assets/json/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#ff5a78"
  image: assets/logos/android-app-logo.png
  fullscreen: true
  android_12:
    image: assets/logos/android-app-logo.png
    icon_background_color: "#ff5a78"

  web: false
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app-logo.png"
  min_sdk_android: 21