import 'package:flutter/material.dart';
import 'package:meety_dating_app/constants/constants.dart';
import 'package:meety_dating_app/constants/ui_strings.dart';
import 'package:meety_dating_app/models/education_model.dart';
import 'package:meety_dating_app/models/gender_model.dart';
import 'package:meety_dating_app/models/interest.dart';

class ConstantList {
  static List<List<dynamic>> keys = [
    ['1', '2', '3'],
    ['4', '5', '6'],
    ['7', '8', '9'],
    [
      '',
      '0',
      const Icon(
        Icons.backspace_outlined,
        color: Colors.black,
      )
    ],
  ];
  static const List<String> messages = [
    "Complete Your Sign-Up for a World of Connections!",
    "Don't Miss Out! Complete Your Sign-Up Today",
    "Your Dating Adventure Awaits: Finish Sign-Up Now",
    "Ready to Connect? Complete Your Sign-Up!",
    "Join the Conversation: Complete Your Sign-Up",
    "Complete Sign-Up, Meet Your Matches",
    "A New Chapter Awaits: Finish Your Sign-Up",
    "One Step Closer to Connecting: Finish Sign-Up",
    "Ready to Get Started? Complete Your Sign-Up!",
    "Become part of our dating app's community",
  ];
  static List<dynamic> interestList = [
    {"id": 1, "interest": "🎲 Board Games & Puzzles"},
    {"id": 2, "interest": "🛠️ DIY & Crafting"},
    {"id": 3, "interest": "🎤 Stand-Up Comedy"},
    {"id": 4, "interest": "🏃 Running & Marathons"},
    {"id": 5, "interest": "💃 Dancing"},
    {"id": 6, "interest": "🏖️ Beach Activities"},
    {"id": 7, "interest": "⛷️ Skiing & Snowboarding"},
    {"id": 8, "interest": "⛺ Camping & Nature Trips"},
    {"id": 9, "interest": "🌿 Health & Wellness"},
    {"id": 10, "interest": "🍷 Wine Tasting & Winemaking"},
    {"id": 11, "interest": "🍻 Beer Brewing & Craft Beers"},
    {"id": 12, "interest": "🎟️ Vintage Collecting"},
    {"id": 13, "interest": "📱 Online Culture & Memes"},
    {"id": 14, "interest": "📚 Language Learning & Linguistics"},
    {"id": 15, "interest": "🕰️ Historical Reenactment"},
    {"id": 16, "interest": "🏍️ Motorcycle Riding"},
    {"id": 17, "interest": "🔭 Astronomy & Stargazing"},
    {"id": 18, "interest": "🎪 Local Festivals & Events"},
    {"id": 19, "interest": "🧘 Spirituality & Mindfulness"},
    {"id": 20, "interest": "🎮 Board Game Nights"},
    {"id": 21, "interest": "🏙️ Urban Exploration"},
    {"id": 22, "interest": "🕶️ Virtual Reality & Augmented Reality"},
    {"id": 23, "interest": "🏠 Home Renovation & Interior Design"},
    {"id": 24, "interest": "🏄 Stand-up Paddleboarding (SUP)"},
    {"id": 25, "interest": "📷 Film Photography"},
    {"id": 26, "interest": "🌍 Environmental Conservation"},
    {"id": 27, "interest": "👗 Fashion Design"},
    {"id": 28, "interest": "🧗‍♂️ Rock Climbing"},
    {"id": 29, "interest": "🐎 Horseback Riding"},
    {"id": 30, "interest": "♈ Astrology & Horoscopes"},
    {"id": 31, "interest": "⛰️ Outdoor Adventurer and Hiker"},
    {"id": 32, "interest": "📖 Bookworm and Literature Lover"},
    {"id": 33, "interest": "🎶 Indie Music & Live Concerts"},
    {"id": 34, "interest": "🍔 Foodie & Culinary Explorer"},
    {"id": 35, "interest": "🤝 Volunteer & Community Activist"},
    {"id": 36, "interest": "🎮 Gaming & eSports Fanatic"},
    {"id": 37, "interest": "🐾 Pet Lover & Animal Advocate"},
    {"id": 38, "interest": "🎨 Artistic & Creative Soul"},
    {"id": 39, "interest": "✈️ Traveler & Wanderlust Seeker"},
    {"id": 40, "interest": "📱 Tech Geek & Gadget Enthusiast"},
    {"id": 41, "interest": "💪 Fitness Junkie & Gym Goer"},
    {"id": 42, "interest": "🧵 DIY & Craft Enthusiast"},
    {"id": 43, "interest": "🕰️ Vintage Collector & Nostalgia Lover"},
    {"id": 44, "interest": "🌐 Language Enthusiast & Polyglot"},
    {"id": 45, "interest": "🌍 Social Justice Advocate"},
    {"id": 46, "interest": "🎬 Film Buff & Movie Aficionado"},
    {"id": 47, "interest": "📸 Nature Photographer"},
    {"id": 48, "interest": "👠 Fashion & Style Enthusiast"},
    {"id": 49, "interest": "🏈 Sports Fan & Game Day Cheerleader"},
    {"id": 50, "interest": "🏞️ Nature Explore"},
    {"id": 51, "interest": "🎥 Film Connoisseur"},
    {"id": 52, "interest": "🍽️ Culinary Adventurer"},
    {"id": 53, "interest": "🌱 Social Impact Advocate"},
    {"id": 54, "interest": "🎮 Gamer & Geek Culture"},
    {"id": 55, "interest": "🐶 Pet Parent"},
    {"id": 56, "interest": "🎨 Artistic Expression"},
    {"id": 57, "interest": "✈️ Globe Trotter"},
    {"id": 58, "interest": "📱 Tech Enthusiast"},
    {"id": 59, "interest": "💪 Fitness & Wellness"},
    {"id": 60, "interest": "🕰️ Vintage Collector"},
    {"id": 61, "interest": "📚 Linguist & Language Lover"},
    {"id": 62, "interest": "🌿 Environmental Steward"},
    {"id": 63, "interest": "👗 Fashion and Style Aficionado"},
    {"id": 64, "interest": "⚽ Sports Enthusiast"},
    {"id": 65, "interest": "📷 Art of Photography"},
    {"id": 66, "interest": "📚 Book Nerd"},
    {"id": 67, "interest": "📚 Multilingual Book Club"},
    {"id": 68, "interest": "🤔 Philosophy & Existentialism"},
    {"id": 69, "interest": "🌿 Eco-Adventurer"},
    {"id": 70, "interest": "🎥 Independent Cinema"},
    {"id": 71, "interest": "🍲 Gastronomic Anthropologist"},
    {"id": 72, "interest": "🌍 Humanitarian & Aid Work"},
    {"id": 73, "interest": "🕶️ Virtual Reality Enthusiast"},
    {"id": 74, "interest": "🐾 Animal Rights Activist"},
    {"id": 75, "interest": "📝 Creative Writing & Storytelling"},
    {"id": 76, "interest": "🌏 Cultural Nomad"},
    {"id": 77, "interest": "🌱 Sustainable Tech Advocate"},
    {"id": 78, "interest": "🧘 Mindfulness Meditation"},
    {"id": 79, "interest": "🔧 Maker & Inventor"},
    {"id": 80, "interest": "🌍 Human Rights & Social Justice"},
    {"id": 81, "interest": "🎨 Interdisciplinary Artist"},
    {"id": 82, "interest": "✈️ Solo Traveler"},
    {"id": 83, "interest": "🔭 Astronomy Enthusiast"},
    {"id": 84, "interest": "👗 Slow Fashion Advocate"},
    {"id": 85, "interest": "🌄 Adventure Sports Junkie"},
    {"id": 86, "interest": "📸 Photojournalism & Social Issues"},
    {"id": 87, "interest": "🏛️ Ancient History & Archaeology"},
    {"id": 88, "interest": "🎨 Empowerment Through Art"},
    {"id": 89, "interest": "💬 Intellectual Debates"},
    {"id": 90, "interest": "🌍 Social Entrepreneurship"},
    {"id": 91, "interest": "Night Coding"}
  ];

  static List<Gender> genderList = [
    Gender(val: UiString.woman, isSelected: false),
    Gender(val: UiString.man, isSelected: false),
    Gender(val: UiString.trans, isSelected: false),
  ];

  static List<Gender> showMeList = [
    Gender(val: UiString.woman, isSelected: false),
    Gender(val: UiString.man, isSelected: false),
    Gender(val: UiString.everyone, isSelected: false),
  ];
  static List<SexOrientation> sexOrientation = [
    SexOrientation(val: Constants.straight, isSelected: true),
    SexOrientation(
      val: Constants.homoSexual,
      isSelected: false,
    ),
    SexOrientation(
      val: Constants.bisexual,
      isSelected: false,
    ),
    SexOrientation(val: Constants.asexual, isSelected: false),
    SexOrientation(
      val: Constants.demisexual,
      isSelected: false,
    ),
    SexOrientation(val: Constants.pansexual, isSelected: false),
    SexOrientation(
      val: Constants.queer,
      isSelected: false,
    ),
    SexOrientation(val: Constants.bicurious, isSelected: false),
  ];
  static List<LookingFor> lookingForList = [
    LookingFor(val: UiString.openToOptions, isSelected: true),
    LookingFor(val: UiString.longTermRelationship, isSelected: false),
    LookingFor(val: UiString.marriageMinded, isSelected: false),
    LookingFor(val: UiString.casualDating, isSelected: false),
    LookingFor(
      val: UiString.friendship,
      isSelected: false,
    ),
    LookingFor(val: UiString.meaningfulConversations, isSelected: false),
    LookingFor(
      val: UiString.activityPartners,
      isSelected: false,
    ),
    LookingFor(
      val: UiString.noStringsAttached,
      isSelected: false,
    ),
    LookingFor(
      val: UiString.virtualConnections,
      isSelected: false,
    ),
    LookingFor(
      val: UiString.travelCompanions,
      isSelected: false,
    ),
    LookingFor(
      val: UiString.fitnessBuddies,
      isSelected: false,
    ),
    LookingFor(
      val: UiString.gamingEnthusiasts,
      isSelected: false,
    ),
  ];

  static List<String> zodiacSign = [
    UiString.aries,
    UiString.aquarius,
    UiString.cancer,
    UiString.taurus,
    UiString.gemini,
    UiString.leo,
    UiString.virgo,
    UiString.libra,
    UiString.scorpio,
    UiString.sagittarius,
    UiString.capricorn,
    UiString.pisces,
  ];
  static List<Education> educationsLevel = [];
  /* [
    Education(val: Constants.doctoralDeg, isSelected: false),
    Education(val: Constants.professionalDeg, isSelected: false),
    Education(val: Constants.masterDeg, isSelected: false),
    Education(val: Constants.bachelorDeg, isSelected: false),
    Education(val: Constants.associateDeg, isSelected: false),
    Education(val: Constants.someClgNoDeg, isSelected: false),
    Education(val: Constants.highSchool, isSelected: false),
    Education(val: Constants.diploma, isSelected: false),
    Education(val: Constants.lifelongLearner, isSelected: false),
    Education(val: Constants.academicExplorer, isSelected: false),
    Education(val: Constants.creativeSelfTaught, isSelected: false),
    Education(val: Constants.onlineCourseEnthusiast1, isSelected: false),
    Education(val: Constants.militaryServiceGraduate, isSelected: false),
    Education(val: Constants.hybridEducationJourney, isSelected: false),
    Education(val: Constants.collegeDropoutPassionPursuer, isSelected: false),
  ];*/
  static List<String> educationsLevels = [
    UiString.doctoralDeg,
    UiString.professionalDeg,
    UiString.masterDeg,
    UiString.bachelorDeg,
    UiString.associateDeg,
    UiString.someClgNoDeg,
    UiString.highSchool,
    UiString.diploma,
    UiString.lifelongLearner,
    UiString.collegeDropoutPassionPursuer,
    UiString.academicExplorer,
    UiString.creativeSelfTaught,
    UiString.onlineCourseEnthusiast1,
    UiString.militaryServiceGraduate,
    UiString.parentingUniversity,
    UiString.hybridEducationJourney,
  ];
  static List<EducationModel> educationList =
      [] /*[
    EducationModel(
      educationId: "1",
      name: UiString.doctoralDeg,
    ),
    EducationModel(
      educationId: "2",
      name: UiString.professionalDeg,
    ),
    EducationModel(educationId: "3", name: UiString.masterDeg),
    EducationModel(
      educationId: "4",
      name: UiString.bachelorDeg,
    ),
    EducationModel(
      educationId: "5",
      name: UiString.associateDeg,
    ),
    EducationModel(educationId: "6", name: UiString.someClgNoDeg),
    EducationModel(
      educationId: "7",
      name: UiString.highSchool,
    ),
    EducationModel(
      educationId: "8",
      name: UiString.diploma,
    ),
    EducationModel(educationId: "9", name: UiString.lifelongLearner),
    EducationModel(
      educationId: "10",
      name: UiString.collegeDropoutPassionPursuer,
    ),
    EducationModel(
      educationId: "11",
      name: UiString.academicExplorer,
    ),
    EducationModel(educationId: "12", name: UiString.creativeSelfTaught),
    EducationModel(
      educationId: "13",
      name: UiString.onlineCourseEnthusiast1,
    ),
    EducationModel(
      educationId: "14",
      name: UiString.militaryServiceGraduate,
    ),
    EducationModel(educationId: "15", name: UiString.parentingUniversity),
    EducationModel(
      educationId: "16",
      name: UiString.hybridEducationJourney,
    ),
    EducationModel(
      educationId: "17",
      name: UiString.schoolDropOut,
    ),
    EducationModel(
      educationId: "18",
      name: UiString.charteredAccount,
    ),
    EducationModel(
      educationId: "19",
      name: UiString.charteredAccount,
    ),
  ]*/
      ;
  static List<FuturePlan> futurePlan = [
    FuturePlan(val: Constants.startingAFamily, isSelected: false),
    FuturePlan(val: Constants.alreadyAParent, isSelected: false),
    FuturePlan(val: Constants.childFreeByChoice, isSelected: false),
    FuturePlan(val: Constants.blendedFamily, isSelected: false),
    FuturePlan(val: Constants.petParent, isSelected: false),
    FuturePlan(val: Constants.openToCoParenting, isSelected: false),
    FuturePlan(val: Constants.parentingPartner, isSelected: false),
    FuturePlan(val: Constants.careerOverFamily, isSelected: false),
    FuturePlan(val: Constants.travelAndAdventure, isSelected: false),
    FuturePlan(val: Constants.nurturingRelationships, isSelected: false),
    FuturePlan(val: Constants.elderCare, isSelected: false),
    FuturePlan(val: Constants.culturalTraditions, isSelected: false),
    FuturePlan(val: Constants.undecided, isSelected: false),
  ];
  static List<EducationModel> occupation =
      [] /*[
    EducationModel(educationId: "1", name: "Accountant"),
    EducationModel(educationId: "2", name: "Actor/Actress"),
    EducationModel(educationId: "3", name: "Acupuncturist"),
    EducationModel(educationId: "4", name: "Aerospace Engineer"),
    EducationModel(educationId: "5", name: "Air Traffic Controller"),
    EducationModel(educationId: "6", name: "Archaeologist"),
    EducationModel(educationId: "7", name: "Architect"),
    EducationModel(educationId: "8", name: "Artist"),
    EducationModel(educationId: "9", name: "Astronomer"),
    EducationModel(educationId: "10", name: "Baker"),
    EducationModel(educationId: "11", name: "Barista"),
    EducationModel(educationId: "12", name: "Biomedical Scientist"),
    EducationModel(educationId: "13", name: "Biotechnologist"),
    EducationModel(educationId: "14", name: "Cardiologist"),
    EducationModel(educationId: "15", name: "Carpenter"),
    EducationModel(educationId: "16", name: "Cartographer"),
    EducationModel(educationId: "17", name: "Chef"),
    EducationModel(educationId: "18", name: "Cinematographer"),
    EducationModel(educationId: "19", name: "Civil Engineer"),
    EducationModel(educationId: "20", name: "Comedy Writer"),
    EducationModel(educationId: "21", name: "Conservationist"),
    EducationModel(educationId: "22", name: "Content Creator"),
    EducationModel(educationId: "23", name: "Cryptocurrency Analyst"),
    EducationModel(educationId: "24", name: "Customer Support Representative"),
    EducationModel(educationId: "25", name: "Dancer"),
    EducationModel(educationId: "26", name: "Data Analyst"),
    EducationModel(educationId: "27", name: "Dental Hygienist"),
    EducationModel(educationId: "28", name: "Dentist"),
    EducationModel(educationId: "29", name: "Dermatologist"),
    EducationModel(educationId: "30", name: "Dietitian"),
    EducationModel(educationId: "31", name: "Doctor"),
    EducationModel(educationId: "32", name: "Drone Operator"),
    EducationModel(educationId: "33", name: "Economist"),
    EducationModel(educationId: "34", name: "Electrician"),
    EducationModel(educationId: "35", name: "Engineer"),
    EducationModel(educationId: "36", name: "Environmental Policy Analyst"),
    EducationModel(educationId: "37", name: "Environmental Scientist"),
    EducationModel(educationId: "38", name: "Event Planner"),
    EducationModel(
        educationId: "39",
        name: "Exobiologist (Study of Extraterrestrial Life)"),
    EducationModel(educationId: "40", name: "Fashion Designer"),
    EducationModel(educationId: "41", name: "Feng Shui Consultant"),
    EducationModel(educationId: "42", name: "Film Director"),
    EducationModel(educationId: "43", name: "Financial Analyst"),
    EducationModel(educationId: "44", name: "Fire Investigator"),
    EducationModel(educationId: "45", name: "Fitness Trainer"),
    EducationModel(educationId: "46", name: "Florist"),
    EducationModel(educationId: "47", name: "Forensic Scientist"),
    EducationModel(educationId: "48", name: "Forestry Technician"),
    EducationModel(educationId: "49", name: "Game Developer"),
    EducationModel(educationId: "50", name: "Geneticist"),
    EducationModel(educationId: "51", name: "Geologist"),
    EducationModel(educationId: "52", name: "Gerontologist"),
    EducationModel(educationId: "53", name: "Glassblower"),
    EducationModel(educationId: "54", name: "Graphic Designer"),
    EducationModel(educationId: "55", name: "Green Building Consultant"),
    EducationModel(educationId: "56", name: "Hair Stylist"),
    EducationModel(educationId: "57", name: "Horticulturist"),
    EducationModel(educationId: "58", name: "Hydrologist"),
    EducationModel(educationId: "59", name: "Immunologist"),
    EducationModel(educationId: "60", name: "Interior Designer"),
    EducationModel(educationId: "61", name: "IT Professional"),
    EducationModel(educationId: "62", name: "Journalist"),
    EducationModel(educationId: "63", name: "Landscape Architect"),
    EducationModel(educationId: "64", name: "Lawyer"),
    EducationModel(educationId: "65", name: "Librarian"),
    EducationModel(educationId: "66", name: "Linguist"),
    EducationModel(educationId: "67", name: "Linguistic Anthropologist"),
    EducationModel(educationId: "68", name: "Makeup Artist"),
    EducationModel(educationId: "69", name: "Marine Archaeologist"),
    EducationModel(educationId: "70", name: "Marine Biologist"),
    EducationModel(educationId: "71", name: "Marketing Manager"),
    EducationModel(educationId: "72", name: "Materials Engineer"),
    EducationModel(educationId: "73", name: "Meditation Instructor"),
    EducationModel(educationId: "74", name: "Meteorologist"),
    EducationModel(educationId: "75", name: "Music Producer"),
    EducationModel(educationId: "76", name: "Musician"),
    EducationModel(educationId: "77", name: "Neurologist"),
    EducationModel(educationId: "78", name: "Nuclear Engineer"),
    EducationModel(educationId: "79", name: "Nuclear Physicist"),
    EducationModel(educationId: "80", name: "Nurse"),
    EducationModel(educationId: "81", name: "Nutritionist"),
    EducationModel(educationId: "82", name: "Occupational Safety Specialist"),
    EducationModel(educationId: "83", name: "Occupational Therapist"),
    EducationModel(educationId: "84", name: "Orthodontist"),
    EducationModel(educationId: "85", name: "Outdoor Adventure Guide"),
    EducationModel(educationId: "86", name: "Paralegal"),
    EducationModel(educationId: "87", name: "Park Ranger"),
    EducationModel(educationId: "88", name: "Personal Assistant"),
    EducationModel(educationId: "89", name: "Pharmacist"),
    EducationModel(educationId: "90", name: "Photographer"),
    EducationModel(educationId: "91", name: "Physiotherapist"),
    EducationModel(educationId: "92", name: "Pilot"),
    EducationModel(educationId: "93", name: "Podcaster"),
    EducationModel(educationId: "94", name: "Police Officer"),
    EducationModel(educationId: "95", name: "Political Analyst"),
    EducationModel(educationId: "96", name: "Productivity Coach"),
    EducationModel(educationId: "97", name: "Professional Gamer"),
    EducationModel(educationId: "98", name: "Project Manager"),
    EducationModel(educationId: "99", name: "Quantum Computing Researcher"),
    EducationModel(educationId: "100", name: "Radio Show Host"),
    EducationModel(educationId: "101", name: "Radiologist"),
    EducationModel(educationId: "102", name: "Real Estate Agent"),
    EducationModel(educationId: "103", name: "Renewable Energy Consultant"),
    EducationModel(educationId: "104", name: "Research Scientist"),
    EducationModel(educationId: "105", name: "Sales Representative"),
    EducationModel(educationId: "106", name: "Sign Language Interpreter"),
    EducationModel(educationId: "107", name: "Social Media Manager"),
    EducationModel(educationId: "108", name: "Software Developer"),
    EducationModel(educationId: "109", name: "Solar Energy Technician"),
    EducationModel(educationId: "110", name: "Songwriter"),
    EducationModel(educationId: "111", name: "Speech Therapist"),
    EducationModel(educationId: "112", name: "Sports Coach"),
    EducationModel(educationId: "113", name: "Tattoo Artist"),
    EducationModel(educationId: "114", name: "Teacher"),
    EducationModel(educationId: "115", name: "Textile Designer"),
    EducationModel(educationId: "116", name: "Theoretical Physicist"),
    EducationModel(educationId: "117", name: "Tour Guide"),
    EducationModel(educationId: "118", name: "Traffic Engineer"),
    EducationModel(educationId: "119", name: "Traffic Engineer"),
    EducationModel(educationId: "120", name: "Transcriptionist"),
    EducationModel(educationId: "121", name: "Travel Agent"),
    EducationModel(educationId: "122", name: "Truck Driver"),
    EducationModel(educationId: "123", name: "Underwater Archaeologist"),
    EducationModel(educationId: "124", name: "Underwater Photographer"),
    EducationModel(educationId: "125", name: "Urban Planner"),
    EducationModel(educationId: "126", name: "UX/UI Designer"),
    EducationModel(educationId: "127", name: "Vascular Surgeon"),
    EducationModel(educationId: "128", name: "Veterinarian"),
    EducationModel(educationId: "129", name: "Veterinarian Technician"),
    EducationModel(educationId: "130", name: "Video Game Tester"),
    EducationModel(educationId: "131", name: "Virtual Reality Developer"),
    EducationModel(educationId: "132", name: "Waiter/Waitress"),
    EducationModel(educationId: "133", name: "Web Developer"),
    EducationModel(educationId: "134", name: "Wedding Planner"),
    EducationModel(educationId: "135", name: "Wildlife Biologist"),
    EducationModel(educationId: "136", name: "Wind Turbine Technician"),
    EducationModel(educationId: "137", name: "Writer"),
    EducationModel(educationId: "138", name: "X-ray Technologist"),
    EducationModel(educationId: "139", name: "Yacht Captain"),
    EducationModel(educationId: "140", name: "Yoga Instructor"),
    EducationModel(educationId: "141", name: "Yoga Therapist"),
    EducationModel(educationId: "142", name: "Zoologist")
  ]*/
      ;

  static List<String> futurePlans = [
    UiString.startingAFamily,
    UiString.undecided,
    UiString.alreadyAParent,
    UiString.childFreeByChoice,
    UiString.blendedFamily,
    UiString.petParent,
    UiString.openToCoParenting,
    UiString.parentingPartner,
    UiString.careerOverFamily,
    UiString.travelAndAdventure,
    UiString.nurturingRelationships,
    UiString.elderCare,
    UiString.culturalTraditions,
  ];

  static List<String> vaccinatedList = [
    UiString.vaccinated,
    UiString.notVaccinated,
    UiString.preferNotVaccinated
  ];
  static List<String> personalityList = [
    'ESTJ',
    'ENTJ',
    'ESFJ',
    'ENFJ',
    'ISTJ',
    'ISFJ',
    'INTJ',
    'INFJ',
    'ESTP',
    'ESFP',
    'ENTP',
    'ENFP',
    'ISTP',
    'ISFP',
    'INTP',
    'INFP'
  ];
  static List<String> smokerHabits = [
    "🚭 Non - smoker",
    "🚬🌟Occasional smoker",
    "🚬 Social smoker",
    "🚬🚬 Regular smoker"
  ];

  static List<String> drinkerHabits = [
    "🚱 Non - drinker",
    "🥂 Occasional drinker",
    "🍻 Social drinker",
    "🍷🍷 Regular drinker"
  ];

  static List<String> reportList = [
    'This is a fake profile',
    'Someone under 18 is involved',
    'There\'s nudity or something sexually explicit',
    'Someone is selling something',
    'Abusive or threatening behaviour',
    'In-person physical harm happened',
  ];

  static List<String> msgList = [
    "Discover the magic of connection with our dating app – who knows what you'll find?",
    "Turn 'maybe someday' into 'today' – start using our dating app.",
    "Your next great love story starts here, and it's too good to miss.",
    "Don't miss out on a chance to meet your future partner; they could be one click away!",
    "Turn your 'what ifs' into 'happily ever afters' with our dating app.",
    "Life is too short to wait for love – take a chance and swipe right.",
    "Let destiny take the wheel – join our dating app and let the magic happen.",
    "Don't let your love story remain unwritten – create your own happily ever after with us.",
    "Join our community of love seekers and become the author of your own romantic tale.",
    "Take a leap of faith into the world of online dating – it might just change your life."
  ];
  static List<String> premiumPlanList = [
    "Elevate your Meety experience with Meety Plus! Daily limited swipes, and the power to undo swipes put you in control with limited direct messages. Enjoy up to 39% discounts on direct messages and the 'Visitor section for the Last 7 Days.' Uncover who visited your profile and who's interested. Make every connection count!",
    "Go for Meety Gold, and you'll have a treasure trove of swipes at your disposal – up to 300+ a day! You can send seven direct messages, undo any mistaken swipes, and enjoy the same great discounts as Meety Plus members. But the real gold here is that you get to see who likes you, explore the profiles of visitors from the last 3 days, and have control over who views your profile. You can even connect with people beyond your usual location.",
    "Indulge in Meety Platinum - an extraordinary experience. Unlimited swipes, direct messages, and the power to undo await. Enjoy up to 39% off on direct messages. Discover who's smitten, explore recent visitors, and have control. Experience an advanced matching algorithm. Upgrade to Meety Platinum and create a work of art in your love life."
  ];
  static List<String> premiumPlanList2 = [
    "It's a step up that makes every swipe more exciting",
    "It's like having the Golden key to finding your ideal match.",
    "It's like having a personal matchmaker, ensuring you find the perfect connection."
  ];
  static List<String> getMoreMessageList = [
    "Can connect one-on-one with potential matches",
    "No more waiting for responses in a crowded chat, Connect like a pro with direct messages!",
    "Get noticed, get replied to, and get ready for amazing conversations",
    "Direct messages – your secret weapon for sparking real connections",
    "Skip the small talk and dive straight into meaningful conversations with potential matches",
    "Don't pass up the opportunity to create connections that last a lifetime!",
    "It's your chance to build meaningful connections that go beyond the swipe. Give it a try and see where the conversation takes you!",
    "Get ready to experience the thrill of direct messages! It's like having a private chat room for two. The best conversations start here. Grab your chance to connect in a more personal and genuine way!",
    "Direct messages are your golden ticket to deeper connections. Say hello to smoother chats and goodbye to the waiting game.",
    "Break free from the swipe and dive into conversations that matter. Don't miss out on the chance to discover the beauty of direct messaging!",
    "Feel the excitement of direct messages - your direct line to meaningful connections. No more waiting, just authentic conversations with potential matches. Unlock this feature now and start chatting with a personal touch.",
    "With direct messages, you're not just sending messages; you're creating memories. Start chatting your way to unforgettable moments.",
    "Unlock the magic of direct messages and connect with potential matches like never before. Start your journey to meaningful connections today.",
    "Say goodbye to swiping frustrations and hello to 50 opportunities for genuine connections. Make your story with direct messages today!",
    "With direct messages, you have the power to create friendships, sparks, and connections that matter. Take a step towards unforgettable conversations.",
    "Every message is a chance for love, friendship, or a meaningful connection. Get 50 messages and set your heart in motion.",
    "Whether you're on a path to start a family, a devoted pet parent, or exploring a world of cultural traditions, 'Direct Messages' can connect you to someone special. With 50 messages in your pocket, you have the power to find the perfect match for your journey, whatever it may be. Let's get started!",
    "Whether you're starting a family, cherishing your career, embracing adventure, or nurturing relationships, 'Direct Messages' is your key to finding the perfect connection. With 50 messages, you're not just starting conversations; you're starting life's next chapter. Let's make it extraordinary together!",
    "Unlock the power of 'Direct Messages' to achieve your goals, whether it's starting a family, nurturing relationships, or exploring cultural traditions. With 50 messages, your journey begins here.",
    "Your journey is unique, and so are your reasons for connecting. 'Direct Messages' lets you explore career-focused connections, parenting partners, or a world of cultural traditions. Connect with purpose and make lasting memories.",
    "From starting a family to embracing adventure, 'Direct Messages' opens doors to connections that matter. With 50 messages, you're equipped to make your dreams a reality.",
    "Unleash your potential with 'Direct Messages.' our 50 Direct messages feature empower you to write your own story of love, family, and adventure.",
    "connect with people who share your values, whether it's caring for elders, embracing cultural traditions, or starting a family. Start connecting with purpose today."
  ];
  static List<String> getMoreVisitorList = [
    "Unlock the mystery of your profile visitors! Our 'See Your Visitors' feature lets you see who's been peeking at your profile. Discover potential matches who are interested in you. Try it now!",
    "Curious about who's checking out your profile? With our 'See Your Visitors' feature, you can find out! It's like a secret admirer list just for you. Get ready to uncover your fans!",
    "Ever wondered who's interested in you? With 'See Your Visitors,' the guessing game is over. It's your chance to connect with those who find your profile intriguing. Unveil your secret admirers today!",
    "Get the upper hand in the dating game with 'See Your Visitors.' Find out who's been checking you out and take the first step in making meaningful connections. Dive into the world of exciting possibilities!",
    "Your profile has secret admirers waiting to connect. Don't miss out on the opportunity to discover who's interested in you. Try our 'See Your Visitors' feature and connect with those who appreciate your uniqueness!",
    "Your profile is a beacon of interest, and now you can see who's drawn to your light. Our 'See Your Visitors' feature is your key to unveiling the admirers who appreciate your uniqueness. Dive into a world of possibilities!",
    "Ever wondered who lingers on your profile, captivated by your charm? With 'See Your Visitors,' the enigma unravels. Discover those who've taken an interest and embark on a journey of connections waiting to be made.",
    "Your profile is like a magnetic force, attracting interest from others. 'See Your Visitors' is your compass to explore the ones who find you captivating. Don't miss the chance to connect with those who appreciate your allure.",
    "Get ready to connect with those who appreciate your uniqueness. Don't wait; start exploring now!",
    "Feel the excitement of direct messages - your direct line to meaningful connections. No more waiting, just authentic conversations with potential matches. Unlock this feature now and start chatting with a personal touch."
  ];
  static List<String> visitorHeadingList = [
    "Unlock Your Admirers.\nGet 'See Your Visitors' Now.",
    "Curiosity Meets Connection.\nDiscover Who's Interested.",
    "Your Secret Admirers Await.\nTry It Today!",
    "Who's Checking You Out?",
    "See Your Visitors And Connect.",
    "Who's Interested In You?\nFind Out Instantly.",
    "Discover Your Admirers.\nTry 'See Your Visitors'."
  ];
  static List<String> messageHeadingList = [
    "Upgrade To Premium And Send 50 Direct Messages!",
    "Get 50 Messages,\nEndless Possibilities!",
    "Connect With Confidence\n50 Direct Messages Awaits!",
    "More Messages,\nMore Moments,\nMore Memories!",
    "Connect Directly With 'Direct Messages', 50 Chances To Find Your Special Someone!",
    "Unlock 'Direct Messages' For All Your Unique Journeys!",
    "Unlock 'Direct Messages' For Your Unique Journey",
    "Get 50 Direct Messages\nYour Path To Meaningful Connections"
  ];
  static List<String> sentRequestsHeading = [
    "Start a Conversation to Fill Your Connection List",
    "Ready to Connect?",
    "Start Messaging and Discover New Connections!",
    "Haven't sent any messages yet?",
    "Chats Bring Connections",
    "Connect with Profiles with Messages",
  ];
  static List<String> sentRequestsHeadingCaption = [
    "It's time to start making connections! Send a message to someone you're interested in, and their profile will appear here. Don't be shy – take the first step to meet someone new! No worries! It's a blank canvas for your connections. Find someone intriguing, send a message, and watch their profile magically appear here. Let's make Meety moments together!",
    "The magic happens when you start chatting. Send your first message to bring profiles to life in this section.",
    "This space is reserved for your future connections. Get the conversation started, and their profiles will appear here.",
    "No messages, no profiles – it's as simple as that! Say hello, and watch this section fill with potential connections.",
    "Your conversations, your connections. Begin the chat and fill this space with profiles you'll love to meet.",
    "Your chats, your connections. Bring this section to life by sending your first message.",
    "The secret to seeing profiles here? A simple message. Get started on your journey to new connections!",
  ];
  static List<String> backWithoutAnyChanges = [
    "Discover better matches with a complete profile – Let your true self shine!",
    "Make a great first impression – Complete your profile and meet like-minded people!",
    "Find your perfect match – Complete your profile to let others know the real you!",
    "Stand out from the crowd – Enhance your profile for better chances of meeting your soulmate!",
    "Connect on a deeper level – Share more about yourself in your profile and find compatible partners!",
  ];
  static List<String> visitorHeading = [
    "Last Week's Guests",
    "Recent Guests",
    "7-Day Intrigue",
    "Weekly Views",
    "Visitor Spotlight",
  ];
  static List<String> visitorHeadingCaption = [
    "Discover Who's Knocking on Your Digital Doorstep",
    "Peek into the Profiles of Your Recent Week's Visitors",
    "See Who Dropped By in the Last 7 Days",
    "Spot Your Recent Admirers in a Glance",
    "Explore Profiles of Those Who Stepped into Your World",
    "Spot Your Admirers – See Last 7 Days Visitors and Connect with Direct Messages!",
    "Your Weekly Connection Hub – Explore Last 7 Days Visitors",
    "Turn Visits into Connections and Directly Message Your Potential Mates!",
    "7 Days, 7 Connections – Explore Your Recent Admirers Now!",
    "Last Week's Sparks – Dive into Profiles, Message Your Matches!",
    "Spot the Trend – See Weekly Visitors, Message Your Matches!",
    "Your Weekly Fanbase – Connect Swiftly with 7 Days Visitors!",
    "Explore and Chat with Your Recent Visitors!",
    "See and Message Your Last 7 Days Admirers!",
  ];
  static List<String> messageHeading = [
    "Private Chat",
    "Direct, Swift, Yours",
    "Quick Messages",
    "Connect Instantly",
    "Your Direct Line",
    "Direct Inbox",
    "Instant Connection"
  ];
  static List<String> messageHeadingCaption = [
    "Direct Messages, Your Way – Where Connections Unfold",
    "Where Direct Connections Converge and Conversations Flourish",
    "Quench Your Conversation Thirst – Dive into Direct Chats",
    "Direct, Quick, Yours – Where Every Message Matters",
    "Connect One-on-One – Your Personal Messaging Hub",
    "50 Direct Messages to Forge Meaningful Conversations!",
    "Explore Beyond Profiles – Connect Privately with Your Visitors!",
    "Ignite Connections with 50 Direct Messages at Your Fingertips!"
  ];
}
